[project]
name = "niffler"
version = "2.7.0"
description = "Simple and transparent support for compressed files."
authors = ["Pierre Marijon <pierre@marijon.fr>", "Luiz Irber <luiz.irber@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[tasks]

[environments]
default = { features = ["dev", "build"], solve-group="default" }
dev = { features = ["dev", "build"], solve-group = "default" }
msrv = { features = ["msrv", "build"], solve-group = "msrv" }

[feature.msrv.dependencies]
rust = "~=1.74.0"

[feature.msrv.tasks]
check_msrv = "cargo build"

[feature.dev.dependencies]
rust = "~=1.84.0"
cargo-nextest = ">=0.9.78,<0.10"
cargo-llvm-cov = ">=0.6.15,<0.7"

[feature.build.dependencies]
compilers = ">=1.7.0,<1.8"
cmake = ">=3.29.5,<3.30"
make = ">=4.3,<5"

[activation.env]
CARGO_HOME = "$CONDA_PREFIX/.cargo_cache"
PATH = "$PATH:$CARGO_HOME/bin"
