[project]
name = "niffler"
version = "3.0.0"
description = "Simple and transparent support for compressed files."
authors = ["Pierre Marijon <pierre@marijon.fr>", "Luiz Irber <luiz.irber@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]

[tasks]

[environments]
default = { features = ["dev", "build"], solve-group="default" }
dev = { features = ["dev", "build"], solve-group = "default" }
wasm = { features = ["dev", "build", "wasm"], solve-group = "default" }
msrv = { features = ["msrv", "build"], solve-group = "msrv" }

[feature.msrv.dependencies]
rust = "~=1.74.0"

[feature.wasm.dependencies]
rust-std-wasm32-unknown-unknown = "*"

[feature.wasm.tasks]
build-wasm = "cargo build --target wasm32-unknown-unknown --no-default-features --features wasm"

[feature.msrv.tasks]
check_msrv = "cargo build"

[feature.dev.dependencies]
rust = "~=1.84.0"
cargo-nextest = ">=0.9.78,<0.10"
cargo-llvm-cov = ">=0.6.15,<0.7"

[feature.dev.tasks]
install_tools = "cargo install -f cargo-binstall && cargo binstall -y --force cargo-feature-combinations && cargo binstall -y --force cargo-semver-checks"

[feature.build.dependencies]
compilers = ">=1.7.0,<1.8"
cmake = ">=3.29.5,<3.30"
make = ">=4.3,<5"
openssl = "*"
pkg-config = "*"

[activation.env]
CARGO_HOME = "$CONDA_PREFIX/.cargo_cache"
PATH = "$PATH:$CARGO_HOME/bin"
