use thiserror::Error;

/// Errors that can be generated by niffler
#[derive(Debug, Error)]
pub enum Error {
    /// This feature is disabled, you can enable it in cargo dependencies sections.
    #[error("Feature disabled, enabled it during compilation")]
    FeatureDisabled,

    /// This file is shorter than five bytes, it's probably not a compression file or corrupted.
    #[error("File is too short, less than five bytes")]
    FileTooShort,
}
